### ISSUE TITLE
Failed to read config file on Windows

### ISSUE THREAD

**Issue by Explorare** [Rehtt/v2ray-tools#1]
**[env]**
Windows 10 21H2
Python 3.10.6

The path I tried to read
`C:\Users\explo\Documents\Tools\V2RayN\relay_test.json`

**[log]**
```
@explo ➜ V2RayN  python .\api.py -c .\relay_test.json
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\Users\explo\Documents\Tools\V2RayN\api.py", line 125, in <module>
    main(sys.argv[1:])
  File "C:\Users\explo\Documents\Tools\V2RayN\api.py", line 102, in main
    data = json.load(f)
  File "C:\Users\explo\scoop\apps\python\current\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\explo\scoop\apps\python\current\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\explo\scoop\apps\python\current\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\explo\scoop\apps\python\current\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 48 column 20 (char 1027)
```
Spend an hour on this issue and find that the most compatible way to handle Windows path is using `pathlib`.
ref: [Python3 技巧：处理 Windows 和 Mac/Linux 文件路径差异的窍门 - 明月轩 | LibertyDream](https://libertydream.github.io/2019/08/10/Python-3%E5%B0%8F%E6%8A%80%E5%B7%A7-%E4%BE%BF%E6%8D%B7%E5%A4%84%E7%90%86Windows-Mac%E5%92%8CLinux%E4%B8%8A%E7%9A%84%E6%96%87%E4%BB%B6%E8%B7%AF%E5%BE%84/)

帮帮孩子.jpg

**Comment by Rehtt** [comment]
windows环境的还没测试过，这是针对linux环境开发的，而且这个工具是针对服务端开发的

**Comment by Rehtt** [comment]
客户端的话你可以用v2rayn自带的统计

**Comment by Explorare** [comment]
谢谢回复，我最后用 WSL 跑的就没问题了。
